spring:
  datasource:
    url: jdbc:mysql://localhost:3306/communicatewithbhx
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
